### ISSUE TITLE
home page picture loading

### ISSUE THREAD

**Issue by jgregorytweedie** [mayorbcode/cpnt260-final#1]
I noticed when I load up the first image for the first time, it takes about 3 seconds to load, maybe lower the res of the photo or make the image locally loaded? (possibility of how your code fetches the URL could be lagging it)

**Comment by mayorbcode** [comment]
Yeah noticed that too. Will probably link relatively in the future.
    On Thursday, November 5, 2020, 10:39:19 AM MST, 404jaydenNotFound <notifications@github.com> wrote:  
 
 


I noticed when I load up the first image for the first time, it takes about 3 seconds to load, maybe lower the res of the photo or make the image locally loaded? (possibility of how your code fetches the URL could be lagging it)
